### ISSUE TITLE
Normalisation issue

### ISSUE THREAD

**Issue by jrs65** [prisae/pyfftlog#15]
I think there is a normalisation issue within `pyfftlog.fftl`. I'm finding that I need to scale the output of the transform by the centre of the integration range (`kc`) to get the correct results. Here is an example which computes an integral which has an exact result.
```python

# We're going to calculate the integral g(r) = \int_0^\infty sin(r k) e^{-a k} dk
# This has an exact result g(r) = r / (r^2 + a^2)
# (see: https://en.wikipedia.org/wiki/List_of_integrals_of_exponential_functions#Definite_integrals)
import numpy as np
import pyfftlog
from matplotlib import pyplot as plt

a = 5

def f(k):
    return np.exp(-a * k)
    

fig, axes = plt.subplots(2, 1, figsize=(10, 10), sharex=True, sharey=True, gridspec_kw=dict(hspace=0.0))

# We define the transform grid in terms of the final space (r). Here we 
# iterate over pairs of the upper and lower bounds, this will generate 
# different rc/kc values
for logrmin, logrmax in [(-2, 5), (-1, 5), (-3, 4)]:
    n = 1<<16
    dlnr = (logrmax - logrmin) * np.log(10.0) / n

    # Set pyfftlog params and calculate a better kr
    mu = 0.5
    q = -0.5
    kr = 1.0
    kr, xsave = pyfftlog.fhti(n, mu, dlnr, q=q, kr=kr, kropt=2)

    # Calculate the grid in the initial space (k) and the final space (r)
    jc = (n + 1) / 2.0
    rc = 10**((logrmax + logrmin) / 2.0)
    ja = np.arange(n)
    kc = kr / rc

    ra = rc * np.exp((ja - jc) * dlnr)
    ka = kc * np.exp((ja - jc) * dlnr)

    # Use pyfftlog to calculate the integral, we need to apply a sqrt(pi / 2) to get rid of the normalisation
    g = (np.pi / 2)**0.5 * pyfftlog.fftl(f(ka), xsave, rk=kr, tdir=1)
    
    axes[0].loglog(ra, g, label=f"kc = {kc:.2f}")
    axes[1].loglog(ra, g * kc, label=f"kc = {kc:.2f}")

    
    
ra = np.logspace(-3, 5, n)
g_exact = ra / (ra**2 + a**2)
axes[0].loglog(ra, g_exact, "k:", label="Exact")
axes[1].loglog(ra, g_exact, "k:", label="Exact")

axes[0].text(1e-3, 10, "Normal")
axes[1].text(1.e-3, 10, "Scaled by kc")

axes[0].legend()
```

It calculates the results for several integration ranges to demonstrate the dependence on `kc` (upper panel) and shows that the correction seems to remove this (lower panel). The output plot is attached below.
<img width="603" alt="Unknown" src="https://user-images.githubusercontent.com/695206/123685944-18a70580-d804-11eb-985b-414f75577d1d.png">

**Comment by prisae** [comment]
Hi Richard, thanks for reporting this.

I am sorry it does not work out-of-the-box for you. I don't think there is a normalisation issue. fftlog is a pure wrapper around FFTLog, which has been used extensively. pyfftlog is a pure Python implementation of FFTLog. I do suspect it is something else in your example - unfortunately I do not have the bandwidth to debug your code, I am sorry. However, I do have some questions which might give some insights if you could check them:

- Did you try the same example with [fftlog](https://github.com/prisae/pyfftlog)? This is the simple Python-wrapper of the original FFTLog Fortran code - so if you have the scaling issue there, it would mean there is a scaling issue with [FFTLog](http://casa.colorado.edu/~ajsh/FFTLog). And I think this is highly unlikely, as FFTLog has been used extensively. Of course it is not impossible, but you would have to report that issue to Andrew Hamilton.
- Of course it could be that the pure Python version `pyfftlog` introduced some errors. However, with your scaling all the examples in the documentation ([pyfftlog.rtfd.io](https://pyfftlog.rtfd.io)) would be wrong - which would be very strange.

If you could check it with `fftlog` that would be awesome, please keep me posted, I leave this issue open!

Finally, did you have a look at the section 11 of the original FFTLog docs, https://jila.colorado.edu/~ajsh/FFTLog/#trouble ? That might have some hints.

**Comment by jrs65** [comment]
Thanks for the quick reply. I think this one is my problem, the issue being not properly setting the `rk` argument. Sorry for the waste of time, I'll close this now!

**Comment by prisae** [comment]
No problem Richard, better once too much! I hope my little contribution (pyfftlog) is useful for you, but the true credits go to Andrew Hamilton of course.
