### ISSUE TITLE
Cannot import pyfftlog

### ISSUE THREAD

**Issue by ShazAlvi** [prisae/pyfftlog#5]
First of all, thanks for writing this. I am trying to import the library after doing pip install pyfftlog but on the terminal I get the following error, 

from pyfftlog.pyfftlog import fhti, fftl, fht, fhtq, krgood

Any idea what I am doing wrong here? Did I miss a step between pip install and import? 

Thanks.

**Comment by prisae** [comment]
Hi @ShazAlvi . That is strange.

- First, are you on Windows? It shouldn't matter for `pyfftlog`, but it might for `fftlog`.
- You installed `pip install pyfftlog`, not `pip install fftlog`, right?
- There was no error during installation?
- You have `scipy` and `numpy` installed, right? (`pip` should take care of that).
- Do you use `conda`? If so, could you try to install `conda install -c conda-forge pyfftlog`?

**Comment by ShazAlvi** [comment]
Hi @prisae ,

Thank you for the quick reply. 

- I have a Window but the installation was done using a Ubuntu WSL. 
- The installation went without any errors. I can see the pyfftlog folder in the directory. 
- Yes, I have both Scipy and Numpy installed. 
- Sorry, I do not use Conda. I have Python installed and I use it in VS Code. However, even trying to call it on Ubuntu WSL gives the same error. 

I am attaching the pictures below. 

![image](https://user-images.githubusercontent.com/63428526/86590868-b3258d80-bf90-11ea-88e9-18d942694370.png)

![image](https://user-images.githubusercontent.com/63428526/86591048-0f88ad00-bf91-11ea-8030-f39f20f519f5.png)

**Comment by ShazAlvi** [comment]
The installation ended with the following message (I just realized that it is not shown in the image I attached)

Successfully installed pyfftlog-0.2.0

**Comment by prisae** [comment]
Yes, I think you are using the wrong Python. In your path, it says `File "/usr/local/lib/python2.7...` -> Python 2.7 is not supported any longer, not by `numpy` nor by `scipy` nor by `pyfftlog` and not by most packages. And your `pip` did probably use another python.

Can you post the output of `which pip`?

I suggest you download `anaconda` or `miniconda` and use a dedicate Python environment for any scientific task, instead of the Python that comes with your operating system. OS-Python version are usually heavily outdated, and you don't want to mess with the OS-Python environment.

**Comment by ShazAlvi** [comment]
Hi, 

Thanks for the comment. I have two versions on Python (2.7 and 3.8) for work-related reasons. Can you tell me how I can force pip to install in Python 3.8 directory?

**Comment by prisae** [comment]
OK, I understand, fair enough.

If you have both you might have to use `pip3`. Just run `which pip` or `which pip3` to find out. You can not tell pip where to install (as far as I know), instead, you have to find the pip in the relevant environment.

**Comment by ShazAlvi** [comment]
```
which pip
/usr/bin/pip
```

`which pip3`
Does not return anything. Not even an error.

**Comment by prisae** [comment]
So you might not have `pip` installed for python3, and might still have to install it. Did you install anything yet for your python3-environment?

I do not use Windows and do not no the WSL, but from what I heard it is a normal linux system. So, what linux version do you run in WSL?

**Comment by prisae** [comment]
`sudo apt install python3-pip` should do the trick.

**Comment by ShazAlvi** [comment]
So Linux version is, 18.04.2 LTS (Bionic Beaver). I installed Numpy and Scipy after Python 3. The complication is that I would prefer to keep the Ubuntu version to Python 2.7. Since the library that I use for my research is compatible with Python 2.7. But for quite other reasons, I have to use tools in Windows which require Python 3.8. It is a complicated mess (now that I am saying it here).  So I think what I need to do is install pyfftlog on windows with python 3. Do you agree?

**Comment by prisae** [comment]
Well, you can only use `pyfftlog` with Python 3. And I strongly recommend to switch to Python 3, as Python 2 is not supported any longer.

From the problems you describe I would recommend to use virtual environments. Either by using conda or any of the other virtual environment tools. This will help you with that, as you can easily have an environment for Python 2.7, one for Python 3.6, one for 3.8, even several for the same Python version but different packages. However, all that still means that you will need Python 3 to use `pyfftlog`.

I close this issue, as I don't think it is a problem related to `pyfftlog` - however, feel free to keep asking questions here, I am happy to help!

**Comment by prisae** [comment]
List of supported versions of Python:
https://devguide.python.org/#status-of-python-branches

More info about conda virtual environments (alternatives are, e.g.,  `virtualenv`, `pipenv`)
https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

**Comment by ShazAlvi** [comment]
Thank you for all the useful information and for the links. I am new to Python so I do not know a lot of Pythonic tricks. Will look into them. As for the current problem, I installed it in Windows using pip in Python 3.8 (same command for Python 3) and I am able to import it in Python 3.8 so VS should not have a problem now. Thank you so much for your time and prompt responses.

**Comment by prisae** [comment]
No problem at all, I am glad it worked in your windows version now, great!
