### ISSUE TITLE
Error xsave indices

### ISSUE THREAD

**Issue by ShazAlvi** [prisae/pyfftlog#6]
On using n = 10, the following error occurs,

```
  File "C:\Users\Shaz_Alvi\AppData\Local\Programs\Python\Python38\lib\site-packages\pyfftlog\pyfftlog.py", line 564, in fht
    fct = fhtq(fct, xsave, tdir)
  File "C:\Users\Shaz_Alvi\AppData\Local\Programs\Python\Python38\lib\site-packages\pyfftlog\pyfftlog.py", line 626, in fhtq
    fct[2*m-1] = ar*xsave[2*m+1] - ai*xsave[2*m+2]
IndexError: index 13 is out of bounds for axis 0 with size 13
```

Upon inspecting, the function pyfftlog.fhti and fhtq, it appears the problem might be in, 

`m = np.arange(1, n//2, dtype=int)` in fhtq. This is different from `m = np.arange(1, (n+1)/2)` in fhti. These arrays have different values as I checked when the print them for the same value of n that I use in my code. At least, that is my understanding and I might be wrong about it.

**Comment by prisae** [comment]
Could you send me some more information, how can I reproduce it? (A minimum working example would be great.) I'll have a look tomorrow!

**Comment by ShazAlvi** [comment]
Yes, of course. Sorry for the incomplete information. Here are the parameters that I am using, 


```
#------Parameters of the fftlog algorithm
# Range of periodic interval
logrmin = np.log(k[0])
logrmax = np.log(k[len(k)-1])
# Number of points (Max 4096)
n = 10
# Order mu of Bessel function
mu = 0
# Bias exponent: q = 0 is unbiased
q = 0
# Sensible approximate choice of k_c r_c
kr = 1
# Tell fhti to change kr to low-ringing value
# WARNING: kropt = 3 will fail, as interaction is not supported
kropt = 1
# Forward transform (changed from dir to tdir, as dir is a python fct)
tdir = 1
logrc = (logrmin + logrmax)/2
nc = (n + 1)/2.0
dlogr = (logrmax - logrmin)/n
dlnr = dlogr*np.log(10.0)
kr, xsave = pyfftlog.fhti(n, mu, dlnr, q, kr, kropt)
logkc = np.log10(kr) - logrc
rk = 10**(logrc - logkc)
#------Parameters of the fftlog algorithm
```
The input function is, 
`ar = Temp_Source[j,:]*Density_Source_At_Dirac[:]*P_Pk[:]`

Here, these are the values of the function at discrete values of the input argument for each integer j (one list for one integer j which is looped over). I am not sure what else information you would need. Please let me know what else you would like to know. 

Thank you, once again.

**Comment by prisae** [comment]
What is `k`? What would help is an example that I can run. 10 points is *very* few, how many decades do you cover?

**Comment by prisae** [comment]
My point is - even not knowing exactly your script, I doubt you will ever get a sensible transform with only 10 points.

Here you can find two examples:
https://pyfftlog.readthedocs.io/en/latest/examples/index.html

and on the original website you can find some more useful information:
https://casa.colorado.edu/~ajsh/FFTLog/

**Comment by ShazAlvi** [comment]
I figured out my mistake. I misunderstood the meaning of n.

**Comment by prisae** [comment]
Glad it works now!
