### ISSUE TITLE
Question about fftl (FFTLog) routine

### ISSUE THREAD

**Issue by ShazAlvi** [prisae/pyfftlog#7]
In an effort to understand the underlying math, I tried to play around with the test file included. I wanted to test the fftl routine by computing the Fourier sine transform using fftl by giving it a np.cos(x) function as an input. I was expecting that the \tilde{A}(k) should have been just a peek around 1 because the input function has a only one frequency of cos. |But the output was fairly different. I am attaching the output plot and the file. 
[fftlogtest.txt](https://github.com/prisae/pyfftlog/files/4898158/fftlogtest.txt)

Perhaps, I am missing some fundamental mathematical point. If you can provide some insight, it would be very helpful. Thanks. 

![image](https://user-images.githubusercontent.com/63428526/87066666-381fd980-c213-11ea-8ab3-2c29f3bc21d1.png)

**Comment by prisae** [comment]
Did you model your function smooth in log-space? Normally, your `k` would span several orders of magnitude (see examples). If you made it smooth in linear-space (the normal cosine) then FFTLog is not the way to go. FFTLog is for logarithmically sampled data.

Anyway, for the mathematical concept I have to refer to Hamilton and https://jila.colorado.edu/~ajsh/FFTLog/ . In https://github.com/prisae/fftlog I wrote a Python-wrapper for that, and in https://github.com/prisae/pyfftlog I wrote a pure Python implementation for it. However, these two projects are, in a way, "pure coding tasks" that have nothing to do with the underlying maths, with the objective to bring FFTLog to the Python world. I would not claim that I know every bit of the ins and outs of the algorithm.

From Hamilton's documentation I cite here point 11. It might give you some hints in what direction to search:

> 11. Troubleshooting
> FFTLog does not work well with my function. What should I do?
> - Diagnose the problem. Is there ringing and aliasing? Read §10. Is your function ‘smooth’ (contains only low frequencies) in logarithmic space? If not, then FFTLog may not be appropriate to your problem.
> - Use a low-ringing value of k_0r_0,  §8.
> - Experiment with different values of the bias index q.
> - Enlarge the periodic interval over which you specify your function. Extrapolate your function sensibly: padding with zeros may not be enough.
> - Increase the resolution, by reducing the logarithmic spacing of points. If your function is adequately ‘smooth’, then increasing the resolution should, eventually, have no effect. If continuing to increase the resolution continues to have an effect, then your function is not ‘smooth’.
> - Use another code. 

While I am happy to provide help and bug fixes if there are issues with my implementation I won't be of help with actually applying it to "function X" to solve "problem Y!, sorry. All I can refer to are the [docs](https://pyfftlog.readthedocs.io/) and the [docs of Hamilton](https://jila.colorado.edu/~ajsh/FFTLog/), as well as the paper [Hamilton (2000)](http://dx.doi.org/10.1046/j.1365-8711.2000.03071.x).

**Comment by ShazAlvi** [comment]
Thanks for your answer. To answer your question, the function appears to be smooth in log space. 

I understood somethings and got the code to work as I was expecting. I will post here my findings for anyone who is seeking it. The reconstruction of the input function is done using the following integral, 
![image](https://user-images.githubusercontent.com/63428526/87149444-859e5400-c2b0-11ea-84c5-06d199253990.png)
I got this integral by using the integral is the document and using the orthonormality of sine integrals (I might have missed a constant of normalization) which might affect the scaling of the following results. 

The following analysis is for trying to recover a sine function from the sine Fourier transform (mu=0.5).

The following graphs show the plot of a(k) against k and the input and reconstructed functions. The limits are from 0 (on log scale E-3)to 2$\pi$ (on log scale 0.798). The result is unbiased (q=0) and kr = 1. The number of terms is 300.
![image](https://user-images.githubusercontent.com/63428526/87145961-816f3800-c2aa-11ea-9ce4-b7a00158f1f7.png)
The peak in a(k) seems to be at the right position but the reconstruction is fairly bad. 

Increasing the number of terms is not too useful as shown in the following plot for 2000 terms. 
![image](https://user-images.githubusercontent.com/63428526/87146030-9fd53380-c2aa-11ea-9d58-055df69e5320.png)

Changing the bias to a 1 gives the following plot (for n=300),
![image](https://user-images.githubusercontent.com/63428526/87146185-d743e000-c2aa-11ea-8d1a-3675a57af1ca.png)
The result does not change on increasing the number of points.

Changing the bias to -1 make things even worse and the results remain unchanged on changing the number of points.  So the bias is now set to 0.
![image](https://user-images.githubusercontent.com/63428526/87146389-2ab62e00-c2ab-11ea-979f-4be272a174f5.png)
The result seem to stabilize on using a kr = 0.01.  This result does not change appreciably when number of points are increased. ![image](https://user-images.githubusercontent.com/63428526/87146939-0575ef80-c2ac-11ea-8a95-d4b040e0ed38.png)
On using a normalization constant of np.sqrt(2/np.pi) in fftl, you get the following plot for the same details as in the previous plot. The fit is slightly different. I understood that the constant should be there as it is a part of the fourier sine transform as explained in the documents but may be it is not taken into account in the code or perhaps I am making a mistake but it should affect anything more than the scaling factor. 
![image](https://user-images.githubusercontent.com/63428526/87148789-52a79080-c2af-11ea-8d60-7d4756dfcb70.png)
If for the same configuration, the logrmax is increased to 10pi, then the reconstruction becomes significantly better, and so does the distribution of ak in the k space. 
![image](https://user-images.githubusercontent.com/63428526/87148850-75d24000-c2af-11ea-88b8-526e9dad874d.png)
And finally, when the kr = 0.016 using 300 points you get a pretty good fit. 
![image](https://user-images.githubusercontent.com/63428526/87149057-d792aa00-c2af-11ea-9861-25c7068c612a.png)
The output remains stable until 1900 points but then unwanted wiggles start to appear in the reconstructed function. 
![image](https://user-images.githubusercontent.com/63428526/87149257-2c362500-c2b0-11ea-9e06-d1a4db7c8832.png)
As the last word I will just add the location of kr can badly affect the reconstruction of the function and I found the correct values by trial and error. As an example,. the following plot is made for kr = 0.1,
![image](https://user-images.githubusercontent.com/63428526/87149608-de6dec80-c2b0-11ea-8d20-fb0807490131.png)

**Comment by prisae** [comment]
Thanks @ShazAlvi for the examples, interesting. However, I think we speak of different log-spaces. I can see that your `r`-space is logarithmic. But your `k`-space isn't.

An example of the FFTLog (for the Fourier, not the Hankel transform) is given here:
https://pyfftlog.readthedocs.io/en/latest/examples/geophysical_em.html

![sphx_glr_geophysical_em_001](https://user-images.githubusercontent.com/8020943/87150163-db273080-c2b1-11ea-80c6-b5803623c06b.png)

As you can see, both frequency and time are smooth on a log-scale.

Not sure if this could help in your case, but it might give you some ideas how to improve your results.

**Comment by ShazAlvi** [comment]
Hi @prisa. You are welcome. Thanks for sharing this. The k's are in log space (because that part of the test file which determines k are still the same, I did not alter that so I am assuming that it is still in log space), I am not plotting them in log scale because it helped me visualize when the scale was linear. Here is my output for the last stable plot (n=300, kr=0.016). The distribution of ak is fairly smooth. 

![image](https://user-images.githubusercontent.com/63428526/87150571-a10a5e80-c2b2-11ea-8152-9005893b6bb8.png)

Feel free to close the issue, if you feel like it since the issue for which it was opened has been resolved.

**Comment by prisae** [comment]
Great, I didn't see that you finally got a good result, great!

One question, did you use the feature to get the best `kr` value automatically?

**Comment by prisae** [comment]
Yes, I'll close, but I leave the `Question` tag, so other users might find it easier and see your solutions. Thanks for sharing!

**Comment by prisae** [comment]
Here, with `kropt=1`, it will return you the best `kr`-value.
`kr, xsave = pyfftlog.fhti(n, mu, dlnr, q, kr=1, kropt=1)`

**Comment by ShazAlvi** [comment]
You are welcome. 

I found the right value of kr by trial and error. kropt is set to 1 so when I give it the value of 0.016, the "optimized" value is set to around  0.01587, so not too far from my guess. kropt was always set to 1 but I did not consider the best-guess returned (simply forgot). I just did a quick check, if kr = 1 the optimized value returned is 0.99. The optimized values returned do not seem to be very far away from the best guess values.

**Comment by ShazAlvi** [comment]
Is there a way to calculate kr to a reasonably close value which can give a good result?

**Comment by prisae** [comment]
> Is there a way to calculate kr to a reasonably close value which can give a good result?

https://jila.colorado.edu/~ajsh/FFTLog/#lowring

**Comment by ShazAlvi** [comment]
Thanks.

**Comment by ShazAlvi** [comment]
There is one thing which I forgot to mention in the post above. I had to introduce a negative sign with the integral that I mentioned. I have not completely understood the source of that negative sign, however given that I was getting stable results 

> Thanks @ShazAlvi for the examples, interesting. However, I think we speak of different log-spaces. I can see that your `r`-space is logarithmic. But your `k`-space isn't.
> 
> An example of the FFTLog (for the Fourier, not the Hankel transform) is given here:
> https://pyfftlog.readthedocs.io/en/latest/examples/geophysical_em.html
> 
> ![sphx_glr_geophysical_em_001](https://user-images.githubusercontent.com/8020943/87150163-db273080-c2b1-11ea-80c6-b5803623c06b.png)
> 
> As you can see, both frequency and time are smooth on a log-scale.
> 
> Not sure if this could help in your case, but it might give you some ideas how to improve your results.

I was looking through this example and I have a quick question: Why do you have to multiply a negative sign with the summation for sine?

**Comment by prisae** [comment]
Where do you mean exactly (which line of code where I multiply by -1).

**Comment by ShazAlvi** [comment]
Sorry, I meant in the FFTLog code. These are the lines I am referring to, 

```
    if mu > 0:
        f_resp += -1j*t2f_f_spline(np.log(ftpts))/np.pi/2
        t_resp_sin = -f2t_t_spline(np.log(ftpts))/np.pi*2
    else:
        f_resp += t2f_f_spline(np.log(ftpts))/np.pi/2
        t_resp_cos = f2t_t_spline(np.log(ftpts))/np.pi*2
```

**Comment by prisae** [comment]
That comes directly from the definition of the Fourier transform. See, e.g.,
- https://en.wikipedia.org/wiki/Sine_and_cosine_transforms#Relation_with_complex_exponentials
- https://empymod.readthedocs.io/en/stable/transforms.html#notes-on-fourier-transform

where the second link in particular is how it is implemented in the example you mention.

**Comment by ShazAlvi** [comment]
Thanks a bunch!!!

**Comment by prisae** [comment]
@ShazAlvi , would you be willing to share your code (just the example)? Now on the weekend I'd have some time to look at it, and it would be great to create an example for the gallery for future users!

**Comment by ShazAlvi** [comment]
Hi, Sorry, I just realized there was a message here. Sure, I will share my code with you. Just give me a day or two to clean up the code and also add some helpful comments.

**Comment by prisae** [comment]
Great, thanks. Feel free to make a PR with the example in here: https://github.com/prisae/pyfftlog/tree/master/examples or paste the code here or email it to me. Rest assured that either way I will give due credit to you!

**Comment by ShazAlvi** [comment]
Hello @prisae ,

Sorry for taking a long time to come back to you. I have cleaned the file I made for the plots in this thread. I am very new to GitHub so I do not know how things work here and what is a Pull Request (I am assuming that is what you mean by PR). Can you help me with creating the Pull Request?

**Comment by prisae** [comment]
Great! Well, there are two ways it would be helpful.

1. The quick and easy way is to post it here.

2. The longer way is to make a pull request (PR):
- fork the repo to your GitHub
- make a new branch
- add your file (as it is an example it would live in `/pyfftlog/examples/`
- from the branch in your fork you should then be able to make a PR

If you do make a PR you might also want to check if it is flake8-compatible and if the sphinx-doc build with the example (but I can do these things as well later on)

**Comment by ShazAlvi** [comment]
You should receive a Pull Request. I hope I did everything right. I see myself using GitHub in the future as well, so I prefer to get used to it. Let me know if I have to do anything.
